config/routes.rb
Rails.application.routes.draw do
  devise_for :clients, controllers: {
    sessions:      'clients/sessions',
    password:      'clients/passwords',
    registrations: 'clients/registrations'
  }

  devise_for :providers, controllers: {
    sessions:      'providers/sessions',
    password:      'providers/passwords',
    registrations: 'providers/registrations'
  }

  devise_for :adms, controllers: {
    sessions:      'adms/sessions',
    password:      'adms/passwords'
  }

  resources :products
  resources :purchases

  get '/set_locale/:locale', to: 'application#set_locale', as: 'set_locale'

  get  '/shopping_cart', to: 'shopping_cart#index'
  post '/add_to_cart/:product_id', to: 'shopping_cart#add_to_cart', as: 'add_to_cart'
  post '/remove_one_from_cart/:product_id', to: 'shopping_cart#remove_one_from_cart', as: 'remove_one_from_cart'
  post '/remove_all_from_cart/:product_id', to: 'shopping_cart#remove_all_from_cart', as: 'remove_all_from_cart'

  root to: "home#index"

  get "adms/control_panel" => "adms/control_panel#index"

  post "accept_provider/:provider_id" => "adms/control_panel#accept_provider", as: "accept_provider"
  post "reject_provider/:provider_id" => "adms/control_panel#reject_provider", as: "reject_provider"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @products = Product.all
  end
end

app/views/home/_menu.html.erb
<nav class="navbar-text menu">
  <%= link_to root_path do %>
    <%= image_tag("supplier-market.jpeg", size: "60x50", alt: "Supplier market") %>
  <% end %>

  <ul class="menu-list">
    <% if client_signed_in? %>
      <li class="user"> <i class="fa fa-user-circle-o" aria-hidden="true"></i>
        <ul>
          <li> <%= t('.logged_as')  %> <strong><%= current_client.name.titleize %></strong> </li>

          <li>
            <%= t('.logged_as', { email: current_client.email }) %>
            <%= link_to t('.my_cart', { count: session[:shopping_cart].try(:map) { |product| product["quantity"] }.try(:sum) }), shopping_cart_path, class: 'navbar-link'%> |
          </li>

          <li> <%= link_to t('.edit_profile'), edit_client_registration_path, class: 'navbar-link' %> | </li>

          <li>
            <i class="fa fa-sign-out" aria-hidden="true"></i>
            <%= link_to t('.sign.out'), destroy_client_session_path, class: 'navbar-link', method: :delete %>
          </li>
        </ul>
      </li>
    <% elsif provider_signed_in? %>
      <li class="user"> <i class="fa fa-user-circle-o" aria-hidden="true"></i>
        <ul>
          <li> <%= t('.logged_as') %> <strong><%= current_provider.name.titleize %></strong> </li>

          <li>
            <i class="fa fa-shopping-cart" aria-hidden="true"></i>
            <%= link_to t('.my_cart', { count: session[:shopping_cart].try(:map) { |product| product["quantity"] }.try(:sum) }), shopping_cart_path, class: 'navbar-link'%>
          </li>

          <li> <%= link_to t('.product.new'),    new_product_path,                class: 'navbar-link' %> </li>
          <li> <%= link_to t('.product.plural'), products_path,                   class: 'navbar-link' %> </li>
          <li> <%= link_to t('.edit_profile'),   edit_provider_registration_path, class: 'navbar-link' %> </li>

          <li>
            <p>
              <i class="fa fa-sign-out" aria-hidden="true"></i>
              <%= link_to t('.sign.out'), destroy_provider_session_path, class: 'navbar-link', method: :delete %>
            </p>
          </li>
        </ul>
      </li>
    <% elsif adm_signed_in? %>
      <li class="user"> <i class="fa fa-user-circle-o" aria-hidden="true"></i>
        <ul>
          <li> <%= t('.logged_as')  %> <strong><%= current_adm.name.titleize %></strong> </li>
          <li> <%= link_to t('.product.new'),    new_product_path,            class: 'navbar-link' %> </li>
          <li> <%= link_to t('.product.plural'), products_path,               class: 'navbar-link' %> </li>
          <li> <%= link_to t('.edit_profile'),   edit_adm_registration_path,  class: 'navbar-link' %> </li>

          <li>
            <i class="fa fa-sign-out" aria-hidden="true"></i>
            <%= link_to t('.sign.out'), destroy_adm_session_path, class: 'navbar-link', method: :delete %>
          </li>
        <% else %>
          <li> <%= link_to t('.sign.in.client'),   new_client_session_path,   class: 'navbar-link'  %> </li>
          <li> <%= link_to t('.sign.in.provider'), new_provider_session_path, class: 'navbar-link'  %> </li>
        <% end %>
        </ul>
      </li>
  </ul>

  <% if I18n.locale == :en %>
    <%= link_to set_locale_path(locale: :pt), class: "locale-button" do %>
      <%= image_tag "gb-flag.svg" %>
    <% end %>
  <% else %>
    <%= link_to set_locale_path(locale: :en), class: "locale-button" do %>
      <%= image_tag "br-flag.svg" %>
    <% end %>
  <% end %>
</nav>

app/views/home/index.html.erb
<h2><%= t(".title") %></h2>

<% if adm_signed_in? || client_signed_in? || provider_signed_in? %>
  <table>
    <tbody>
      <% @products.each  do |product| %>
        <tr class="products">
          <td> <%= image_tag "box.svg", width: "180px" %> </td>
          <td> <%= product.name.titleize %> </td>
          <td> R$ <%= product.price.round(2) %> </td>
          <td>
            <%= button_to add_to_cart_path(product_id: product.id), class: "btn btn-success", method: :post, remote: true do %>
              <%= t('.buy') %> <i class="fa fa-shopping-cart" aria-hidden="true"></i>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>