config/routes.rb
Rails.application.routes.draw do
  devise_for :clients, controllers: {
    sessions:      'clients/sessions',
    password:      'clients/passwords',
    registrations: 'clients/registrations'
  }

  devise_for :providers, controllers: {
    sessions:      'providers/sessions',
    password:      'providers/passwords',
    registrations: 'providers/registrations'
  }

  devise_for :adms, controllers: {
    sessions:      'adms/sessions',
    password:      'adms/passwords'
  }

  resources :products
  resources :purchases

  get '/set_locale/:locale', to: 'application#set_locale', as: 'set_locale'

  get  '/shopping_cart', to: 'shopping_cart#index'
  post '/add_to_cart/:product_id', to: 'shopping_cart#add_to_cart', as: 'add_to_cart'
  post '/remove_one_from_cart/:product_id', to: 'shopping_cart#remove_one_from_cart', as: 'remove_one_from_cart'
  post '/remove_all_from_cart/:product_id', to: 'shopping_cart#remove_all_from_cart', as: 'remove_all_from_cart'

  root to: "home#index"

  get "adms/control_panel" => "adms/control_panel#index"

  post "accept_provider/:provider_id" => "adms/control_panel#accept_provider", as: "accept_provider"
  post "reject_provider/:provider_id" => "adms/control_panel#reject_provider", as: "reject_provider"
end

app/controllers/shopping_cart_controller.rb
class ShoppingCartController < ApplicationController
  before_action :set_product_id, only: [:add_to_cart, :remove_one_from_cart, :remove_all_from_cart]
  before_action :check_shopping_cart

  def index
    @shopping_cart = ShoppingCart.cart_formatted(session[:shopping_cart])
  end

  def add_to_cart
    session[:shopping_cart] = ShoppingCart.add_to_cart(session[:shopping_cart], @_product_id)

    flash[:success] = "Product added to cart!"
    head :ok
  end

  def remove_one_from_cart
    session[:shopping_cart] = ShoppingCart.remove_one_from_cart(session[:shopping_cart], @_product_id)
    head :ok
  end

  def remove_all_from_cart
    session[:shopping_cart] = ShoppingCart.remove_all_from_cart(session[:shopping_cart], @_product_id)
    head :ok
  end

  private

  def set_product_id
    @_product_id = params[:product_id]
  end

  def check_shopping_cart
    session[:shopping_cart] = [] unless session[:shopping_cart]
  end
end

app/views/shopping_cart/index.html.erb
  <div class="shopping-cart">
    <div class="title">
      <%= t(".title") %>
    </div>

    <% @shopping_cart.each  do |cart_item| %>
      <div class="item">
        <div class="buttons">
          <%= button_to "X", remove_all_from_cart_path(product_id: cart_item[:product].id), class: "btn btn-danger", remote: true %>
          <%= button_to "❤", root_path, class: "btn btn-primary", remote: true %>
        </div>

        <div class="image">
          <%= image_tag "box.svg", width: "100px" %>
        </div>

        <div class="description">
          <span><%= cart_item[:product].name %></span>
          <span><%= cart_item[:product].description %></span>
        </div>

        <div class="quantity">
          <%= button_to "+", add_to_cart_path(product_id: cart_item[:product].id), class: "btn btn-primary", remote: true %>
          <input type="text" value=<%= cart_item[:quantity] %>>
          <%= button_to "-", remove_one_from_cart_path(product_id: cart_item[:product].id), class: "btn btn-primary", remote: true %>
        </div>

        <div class="total-price">R$<%= cart_item[:product].price.round(2) %></div>
      </div>
    <% end %>
  </div>